{{- if eq .Values.exposure.type "gatewayapi" }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "app.name" . }}-gateway
spec:
  gatewayClassName: {{ .Values.exposure.gatewayapi.gatewayClassName }}
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: {{ .Values.exposure.host }}

    - name: https
      port: 443
      protocol: HTTPS
      hostname: {{ .Values.exposure.host }}
{{- if .Values.exposure.tls.enabled }}
      tls:
        mode: {{ .Values.exposure.tls.mode }}
        certificateRefs:
          - name: {{ .Values.exposure.tls.secret.name }}
            kind: Secret
{{- end }}            
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "app.name" . }}-route
spec:
  parentRefs:
    - name: {{ include "app.name" . }}-gateway
  hostnames:
    - {{ .Values.exposure.host }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.exposure.path }}
      backendRefs:
        - name: {{ include "app.name" . }}-svc
          port: {{ .Values.service.port }}
{{- end }}          