{{- if eq .Values.exposure.type "ingress" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.name" . }}-ing
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}  
spec:
  ingressClassName: {{ .Values.exposure.ingress.className }}
  rules:
    - host: {{ .Values.exposure.host }}
      http:
        paths:
          - path: {{ .Values.exposure.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.name" . }}-svc
                port:
                  number: {{ .Values.service.port }}
{{- if .Values.exposure.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.exposure.host }}
    secretName: {{ .Values.exposure.tls.secret.name }}
{{- end }}
{{- end }}
