{{- if eq .Values.exposure.type "route" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "app.name" . }}-route
  labels:
    {{- include "app.labels" . | nindent 4 }}  
spec:
  host: {{ .Values.exposure.host }}
  path: {{ .Values.exposure.path }}
  to:
    kind: Service
    name: {{ include "app.name" . }}-svc
  port:
    targetPort: http
{{- if .Values.exposure.tls.enabled }}
  tls:
    termination: {{ .Values.exposure.tls.mode | default "edge" | quote }}
{{- if and .Values.exposure.tls.secret.crt .Values.exposure.tls.secret.key }}
    key: |-
{{ .Values.exposure.tls.secret.key | indent 6 }}
    certificate: |-
{{ .Values.exposure.tls.secret.crt | indent 6 }}
{{- if .Values.exposure.tls.secret.ca }}
    caCertificate: |-
{{ .Values.exposure.tls.secret.ca | indent 6 }}
{{- end }}
{{- end }}
{{- end }}

{{- end }}
