{{- if and .Values.exposure.tls.enabled .Values.exposure.tls.secret.create (not .Values.exposure.tls.secret.certManager.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.exposure.tls.secret.name }}
{{- if eq .Values.exposure.type "istio" }}
  namespace: {{ .Values.exposure.istio.namespace }}
{{- else }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{
    if .Values.exposure.tls.secret.ca
  }}
    {{ printf "%s\n%s" (.Values.exposure.tls.secret.crt | trim) (.Values.exposure.tls.secret.ca | trim) | b64enc | quote }}
  {{- else }}
    {{ .Values.exposure.tls.secret.crt | trim | b64enc | quote }}
  {{- end }}
  tls.key: {{ .Values.exposure.tls.secret.key | trim | b64enc | quote }}
{{- end }}