apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/redis

configMapGenerator:
  - name: env-config
    files:
      - env.yaml

generatorOptions:
  disableNameSuffixHash: true
