apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/redis

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml

images:
  - name: ghcr.io/paulovigne/hitcounter
    newTag: dev
