apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/redis

replicas:
  - name: hitcounter
    count: 3

images:
  - name: ghcr.io/paulovigne/hitcounter
    newName: paulovigne/hitcounter
    newTag: v1-prd

patches:
  - target:
      kind: Ingress
      name: hitcounter
    patch: |-
      - op: replace
        path: /spec/ingressClassName
        value: traefik
      - op: replace
        path: /spec/rules/0/host
        value: hitcounter.prd.local

  - target:
      kind: HorizontalPodAutoscaler
      name: hitcounter
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 6
