apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:

##
## Base operator rules
##
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get

- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"

- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch

##
## Rules for apps.vigne.com.br/v1alpha1, Kind: HitCounter
##
- apiGroups:
  - apps.vigne.com.br
  resources:
  - hitcounters
  - hitcounters/status
  - hitcounters/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

##
## Core Kubernetes resources
##
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

##
## Horizontal Pod Autoscaler
##
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

##
## Workloads
##
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

##
## Ingress
##
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - ingresses/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

##
## OpenShift Route
##
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  - routes/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

##
## Istio
##
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  - virtualservices
  - destinationrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

##
## Kubernetes Gateway API
##
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  - httproutes
  - grpcroutes
  - tcproutes
  - tlsroutes
  - udproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
